# Generated by Django 3.1.2 on 2020-10-24 13:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesfromapi',
            name='content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=2000), size=None),
        ),
    ]
