# Generated by Django 3.1.2 on 2020-10-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_auto_20201024_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesfromapi',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
